# Generated by Django 5.0.6 on 2024-06-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_usuario_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='nome',
        ),
    ]
